import React from "react";
import {
  Home,
  Users,
  Layers,
  BarChart2,
  FileText,
  Clock,
  Video,
  Settings,
  Phone,
  BarChart,
  MapPin,
  Activity,
  Mic,
  DollarSign,
} from 'lucide-react'
import { CNavGroup, CNavItem, } from "@coreui/react";

const _nav = [
  {
    component: CNavItem,
    name: "Dashboard",
    to: "/dashboard",
    icon: <Home className="nav-icon" />, 
    group: "",
  },
  {
    component: CNavItem,
    name: "Agents",
    icon: <Users className="nav-icon" />,
    to: "/branch",
    group: "Agents",
  },
  {
    component: CNavItem,
    name: "Department",
    icon: <Layers className="nav-icon" />,
    to: "/department",
    group: "Department",
  },
  {
    component: CNavItem,
    name: "Department Performance",
    icon: <BarChart2 className="nav-icon" />,
    to: "/department-performance",
    group: "Reports",
    feature: "advancedReporting",
  },
  // {
  //   component: CNavItem,
  //   name: "Call Dispositions",
  //   icon: <FileText className="nav-icon" />,
  //   to: "/reports/cdr",
  //   group: "Data & Analytics",
  //   feature: "advancedDispositions",
  // },
  {
    component: CNavItem,
    name: "Reports",
    icon: <BarChart className="nav-icon" />,
    to: "/reports",
    group: "Reports",
    feature: "analytics",
  },
  {
    component: CNavItem,
    name: "Agent Performance",
    icon: <Users className="nav-icon" />,
    to: "/agent-performance",
    group: "Reports",
    feature: "advancedReporting",
  },
  {
    component: CNavItem,
    name: "Follow-ups",
    icon: <Clock className="nav-icon" />,
    to: "/follow-ups",
    group: "Reports",
  },
  {
    component: CNavItem,
    name: "Agent Status Report",
    icon: <Activity className="nav-icon" />,
    to: "/reports/agent-status",
    group: "Reports",
  },
  {
    component: CNavItem,
    name: "Call Logs",
    icon: <Clock className="nav-icon" />,
    to: "/callogs",
    group: "Call Logs",
    feature: "callRecording",
  },
  {
    component: CNavItem,
    name: "IVR Reports",
    icon: <Activity className="nav-icon" />,
    to: "/ivr-reports",
    group: "Reports",
  },
  {
    component: CNavItem,
    name: "Call Uses",
    icon: <FileText className="nav-icon" />, 
    to: "/calluses",
    group: "Call Logs",
  },
  {
    component: CNavItem,
    name: "Call Monitor",
    icon: <Video className="nav-icon" />, 
    to: "/callmonitor",
    group: "Call Logs",
  },
  {
    component: CNavItem,
    name: "Call Settings",
    icon: <Settings className="nav-icon" />,
    to: "/call-settings",
    group: "Settings",
  },
  {
    component: CNavItem,
    name: "Sticky Agents",
    icon: <Phone className="nav-icon" />,
    to: "/sticky-agents",
    group: "Settings",
  },
  {
    component: CNavItem,
    name: "IVR Management",
    icon: <Activity className="nav-icon" />,
    to: "/ivr-management",
    group: "Call Logs",
    feature: "ivrManagement",
  },
  
  {
    component: CNavItem,
    name: "Virtual Numbers",
    icon: <Phone className="nav-icon" />,
    to: "/virtual-numbers",
    group: "Virtual Numbers",
  },
  {
    component: CNavItem,
    name: "Contacts",
    icon: <Users className="nav-icon" />,
    to: "/contacts",
    group: "Contacts",
  },
  {
    component: CNavItem,
    name: "Leads",
    icon: <Users className="nav-icon" />,
    to: "/leads",
    group: "Contacts",
  },
  {
    component: CNavItem,
    name: "Lead Fields",
    icon: <Users className="nav-icon" />,
    to: "/leads/fields",
    group: "Contacts",
  },
  // {
  //   component: CNavItem,
  //   name: "Contact Lists",
  //   icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
  //   to: "/contactlists",
  //   group: "Contact Lists",
  // },
  
  // {
  //   component: CNavGroup,
  //   name: "Campaigns",
  //   icon: <CIcon icon={cilBullhorn} customClassName="nav-icon" />,
  //   items: [
  //     {
  //       component: CNavItem,
  //       name: "Autodial",
  //       to: "/campaigns/autodial",
  //     },
  //     {
  //       component: CNavItem,
  //       name: "Surveys",
  //       to: "/campaigns/surveys",
  //     },
  //   ],
  // },
  {
    component: CNavItem,
    name: "Audio Campaign",
    icon: <Mic className="nav-icon" />,
    to: "/campaigns/audio",
    group: "Campaigns",
    feature: "bulkOperations",
  },
  // {
  //   component: CNavItem,
  //   name: "Users & Teams",
  //   icon: <CIcon icon={cilGroup} customClassName="nav-icon" />,
  //   to: "/users-teams",
  //   group: "Users & Teams",
  // },
  // {
  //   component: CNavItem,
  //   name: "Templates",
  //   icon: <CIcon icon={cilDescription} customClassName="nav-icon" />,
  //   to: "/templates",
  //   group: "Templates",
  // },
  
  {
    component: CNavItem,
    name: "Billing",
    icon: <DollarSign className="nav-icon" />,
    to: "/billing",
    group: "Billing",
  },

  {
    component: CNavItem,
    name: "Settings",
    icon: <Settings className="nav-icon" />,
    to: "/settings",
    group: "Settings",
  },
  {
    component: CNavItem,
    name: "Migrations & Ops",
    icon: <Activity className="nav-icon" />,
    to: "/migrations",
    group: "Settings",
    // Bypass the accessTo/feature filter — admin operations page should
    // always be reachable for business_admin / Employee roles. The page
    // itself enforces server-side authorization via authorizeRoles.
    alwaysVisible: true,
  },
  
  
  // {
  //   component: CNavItem,
  //   name: "Settings",
  //   icon: <CIcon icon={cilSettings} customClassName="nav-icon" />,
  //   to: "/settings",
  //   group: "Settings",
  // },
  {
    component: CNavItem,
    name: "Support Tickets",
    icon: <FileText className="nav-icon" />,
    to: "/tickets",
    group: "Support",
    feature: "ticketing",
  },
];

export default _nav;
